name: Daily Fantasy Sports
favicon: null
layout_spectrum: 0.91619
typography_spectrum: 0.85068
title: 'We love real-money, daily fantasy sports. Do you? Start loving today. '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#191a1e'
    - '#70171b'
    - '#8c4e1b'
    - '#bc9143'
    - '#e3df7c'
  brandStrength: 0.1875
  lightness: 0.4375
  saturation: 0.0625
  rhythmicContrast: 0.25
purpose: []
